//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;


namespace DAL.Models
{

    public partial class DomesticWirePayment
    {
        [Key]
        public long? DomesticWirePaymentId { get; set; }
        public string ABA { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }

        public string IntermediaryBankName { get; set; }
        public string BenificiaryBankName { get; set; }
        public Nullable<long> BankAddressId { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<VendorDomesticWirePayment> VendorDomesticWirePayments { get; set; }
    }
}
