//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;


namespace DAL.Models
{


    public partial class InternationalwirePayment
    {
        [Key]

        public long? InternationalWirePaymentId { get; set; }
        public string SwiftCode { get; set; }
        public string BeneficiaryBankAccount { get; set; }
        public string BeneficiaryBank { get; set; }
        public string IntermediaryBank { get; set; }
        public string BankName { get; set; }
        public Nullable<long> BankAddressId { get; set; }
        public string BeneficiaryCustomer { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<VendorInternationlWirePayment> VendorInternationlWirePayments { get; set; }
    }
}
