//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{

    public partial class PublicationItemMasterMapping
    {
        [Key]
        public long PublicationItemMasterMappingId  { get; set; }
        public long ItemMasterId { get; set; }
        public long ItemClassificationId { get; set; }
        public long ItemGroupId { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate  { get; set; }
        public System.DateTime  UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ItemClassification { get; set; }
        public string PartNumberDescription { get; set; }
        public string PartNumber { get; set; }
        public string PublicationId { get; set; }

		public long PublicationRecordId { get; set; }

    }
}
