//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{

    public partial class ItemMasterATAMapping
    {
        [Key]
        public long ItemMasterATAMappingId { get; set; }
        public long ItemMasterId { get; set; }
        public long ATAChapterId { get; set; }
        public long ATASubChapterId { get; set; }
        public long DashNumberId { get; set; }
        public string PartNumber { get; set; }
        public string ATAChapterCode { get; set; }
        public string ATAChapterName { get; set; }
        public string ATASubChapterDescription { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }

    }
}
