//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{

    public partial class UIRoleEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UIRoleEntity()
        {
            this.UserRoleLevelEntities = new HashSet<UserRoleLevelEntity>();
        }
    
        public long UIRoleEntityId { get; set; }
        public string EntityName { get; set; }
        public long RoleCategorizationLevelId { get; set; }
        public string ModuleName { get; set; }
        public string ScreenName { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual RoleCategorizationLevel RoleCategorizationLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleLevelEntity> UserRoleLevelEntities { get; set; }
    }
}
