//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{
    public partial class VendorContact
    {
        [Key]
        public long VendorContactId { get; set; }

        [ForeignKey("VendorId")]
        public long VendorId { get; set; }

        [ForeignKey("ContactId")]
        public Nullable<long> ContactId { get; set; }

        public bool IsDefaultContact { get; set; }

        public int MasterCompanyId { get; set; }
        public System.DateTime RecordCreateDate { get; set; }
        public Nullable<System.DateTime> RecordModifiedDate { get; set; }
        //public int LastModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public virtual Contact Contact { get; set; }
    }
}
