//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{
    public partial class WorkflowEquipmentList
    {
        [Key]
        public long WorkflowEquipmentListId { get; set; }
        public long WorkflowId { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> AssetTypeId { get; set; }
        public string AssetDescription { get; set; }
        public short Quantity { get; set; }
        public long ActionId { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string PartNumber { get; set; }
    }
}
