//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{


    public partial class WorkflowMaterial
    {
        [Key]
        public long WorkflowMaterialListId { get; set; }
        public long WorkflowId { get; set; }
        public long ItemMasterId { get; set; }
        public long? ItemClassificationId { get; set; }

        [ForeignKey("TaskId")]
        public Nullable<long> TaskId { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<long> UnitOfMeasureId { get; set; }
        public Nullable<short> ConditionCodeId { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> ExtendedCost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ProvisionId { get; set; }
        public Nullable<bool> IsDeferred { get; set; }
        public byte WorkflowActionId { get; set; }
        public string Memo { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string MandatoryOrSupplemental { get; set; }
 

    }
}
