//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DAL.Models
{



    public partial class WorkflowMeasurement
    {
        [Key]
        public long WorkflowMeasurementId { get; set; }
        public long WorkflowId { get; set; }
        public long ItemMasterId { get; set; }
        public string Sequence { get; set; }
        public string Stage { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
        public Nullable<decimal> Expected { get; set; }
        public string DiagramURL { get; set; }
        public string Memo { get; set; }
        public long ActionId { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
