//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using DAL.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterCape
    {
        public long ItemMasterCapesId { get; set; }
        public long ItemMasterId { get; set; }
        public Nullable<long> CapabilityId { get; set; }
        public Nullable<int> MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Capability Capability { get; set; }
    }
}
