//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using DAL.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterAircraftModel
    {
        public long ItemMasterAircraftModelId { get; set; }
        public long ItemMasterId { get; set; }
        public long AircraftModelId { get; set; }
        public string  DashNumber { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        
        public virtual AircraftModel AircraftModel { get; set; }
    }
}
