//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DAL.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;

namespace QuickApp.Pro.ViewModels
{
    public  class VendorViewModel:VendorBaseViewModel
    {
      
        public string VendorCode { get; set; }
        public Int32? CurrencyId { get; set; }
        //[ForeignKey("VendorTypeId")]

        public int VendorTypeId { get; set; }
        public string DoingBusinessAsName { get; set; }
       
        public long? VendorClassificationId { get; set; }
        public long?[] VendorClassificationIds { get; set; }

        public long?[] IntegrationPortalIds { get; set; }

		public long? VendorParentId { get; set; }

		public long Parent { get; set; }
        public string VendorContractReference { get; set; }
       
        public long? AddressId { get; set; }
        public bool IsVendorAlsoCustomer { get; set; }
        public Nullable<long> RelatedCustomerId { get; set; }
        public string VendorEmail { get; set; }
        public bool IsPreferredVendor { get; set; }
        public string LicenseNumber { get; set; }
        public string VendorURL { get; set; }
        public Nullable<bool> IsCertified { get; set; }
        public string CertificationFile { get; set; }
        public Nullable<bool> VendorAudit { get; set; }
        public string VendorAuditFile { get; set; }
        public Nullable<bool> EDI { get; set; }
        public string EDIDescription { get; set; }
        public Nullable<bool> AeroExchange { get; set; }
        public string AeroExchangeDescription { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }

 
        //public Nullable<int> CurrencyId { get; set; }
        public Nullable<byte> DiscountLevel { get; set; }
        public Nullable<bool> Is1099Required { get; set; }
        public Nullable<long> DiscountId { get; set; }

        public Int16? CreditTermsId { get; set; }
        public Nullable<bool> v1099Rent { get; set; }
        public Nullable<bool> v1099RentDefault { get; set; }
        public Nullable<bool> v1099Royalties { get; set; }
        public Nullable<bool> v1099RoyaltiesDefault { get; set; }
        public long? capabilityId { get; set; }
        public Nullable<bool> v1099OtherIncome { get; set; }
        public Nullable<bool> v1099OtherIncomeDefault { get; set; }
        public Nullable<bool> v1099MedicalHealthPayments { get; set; }
        public Nullable<bool> v1099MedicalHealthPaymentsDefault { get; set; }
        public Nullable<bool> v1099NonEmployeeComp { get; set; }
        public Nullable<bool> v1099NonEmployeeCompDefault { get; set; }
        public Nullable<bool> v1099GoldenParachute { get; set; }
        public Nullable<bool> v1099GoldenParachuteDefault { get; set; }
        public Nullable<bool> v1099GrossProceedsPaidToAttorney { get; set; }
        public Nullable<bool> v1099GrossProceedsPaidToAttorneyDefault { get; set; }

        public string VendorParentName { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CustomerTypeDesc { get; set; }
        public string VendorPhone { get; set; }
        public string CountryId { get; set; }
        //public VendorCapabiliy VendorCapabiliy { get; set; }

        //public VendorContact VendorContact { get; set; }

        //public Address Address { get; set; }

        //public virtual VendorClassification VendorClassification { get; set; }

        //public Currency Currency { get; set; }

        //public CreditTerms CreditTerms { get; set; }

        //public virtual VendorType VendorType { get; set; }

        //public VendorShipping VendorShipping { get; set; }

        //public MasterCompany MasterCompany { get; set; }

        public IFormFile VendorFileCertified { get; set; }
        public IFormFile VendorFileAudit { get; set; }
        public string VendorPhoneExt { get; set; }
        public bool IsAddressForBilling { get; set; }
        public bool IsAddressForShipping { get; set; }
        public Nullable<bool> IsAllowNettingAPAR { get; set; }


        public List<VendorProcess1099> Master1099s { get; set; }
    }
}
