//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace QuickApp.Pro.ViewModels
{
    public  class VendorShippingViewModel
    {
        public long VendorShippingId { get; set; }
        public long VendorId { get; set; }
        public long? VendorShippingAddressId { get; set; }
        public string SiteName { get; set; }
        public string ShipVia { get; set; }
        public string ShippingAccountinfo { get; set; }
        public string ShippingId { get; set; }
        public string ShippingURL { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool? IsPrimary { get; set; }

        public string Memo { get; set; }


        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public long? AddressId { get; set; }
    }
}
