//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DAL.Models;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickApp.Pro.ViewModels
{
    public  class VendorPaymentViewModel
    {
        public long VendorPaymentId { get; set; }
        public long VendorId { get; set; }
        public byte DefaultPaymentMethod { get; set; }
       // public string CheckPaymentSite { get; set; }
     //   public Nullable<long> CheckPaymentAddressId { get; set; }
      //  public Nullable<bool> IsCheckPaymentPrimary { get; set; }
        //public string ABARoutingNumber { get; set; }
       // public string AccountNumer { get; set; }
        public string BankName { get; set; }
        public Nullable<long> BankAddressId { get; set; }
        //public string IntlBankSWIFT { get; set; }
       // public string IntlBeneficiaryBankAccount { get; set; }
       // public string IntlBank { get; set; }
        //public Nullable<long> IntlBankAddressId { get; set; }
       // public string IntlBeneficiaryCustomer { get; set; }
        public Nullable<int> MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }



        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string Postal { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }




        public virtual Vendor Vendor { get; set; }
       // public virtual VendorPaymentMethod VendorPaymentMethod { get; set; }
    }
}
