//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DAL.Models;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickApp.Pro.ViewModels
{
    public  class VendorPaymentMethod
    {
       
        public byte VendorPaymentMethodId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
       
        public virtual ICollection<VendorPayment> VendorPayments { get; set; }
    }
}
