//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
namespace QuickApp.Pro.ViewModels
{

    public partial class WorkflowScopeViewModel
    {
       [Key]
    
        public int WorkflowScopeId { get; set; }
        public string WorkflowScopeDescription { get; set; }
        public long MasterCompanyId { get; set; }
        public System.DateTime RecordCreateDate { get; set; }
        public Nullable<System.DateTime> RecordModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowViewModel> Workflows { get; set; }
    }
}
