//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace QuickApp.Pro.ViewModels
{
    public partial class WorkflowViewModel
    {
      
    
        public long WorkflowId { get; set; }
        public string WorkflowDescription { get; set; }
        public string Version { get; set; }
        public Nullable<int> WorkflowScopeId { get; set; }
        public Nullable<long> ItemMasterId { get; set; }
        public string PartNumberDescription { get; set; }
        public string ChangedPartNumber { get; set; }
        public string changedPartNumberDescription { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<System.DateTime> WorkflowExpirationDate { get; set; }
        public Nullable<bool> IsCalculatedBERThreshold { get; set; }
        public Nullable<bool> IsFixedAmount { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public Nullable<bool> IsPercentageOfNew { get; set; }
        public Nullable<decimal> CostOfNew { get; set; }
        public Nullable<byte> PercentageOfNew { get; set; }
        public Nullable<bool> IsPercentageOfReplacement { get; set; }
        public Nullable<decimal> CostOfReplacement { get; set; }
        public Nullable<byte> PercentageOfReplacement { get; set; }
        public string Memo { get; set; }
        public Nullable<long> ManagementStructureId { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
    
    }
}
