//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace QuickApp.Pro.ViewModels { 


    public partial class WorkflowActionAttributeViewModel
    {
        public byte WorkflowActionAttributeId { get; set; }
        public long WorkflowId { get; set; }
        public string WorkflowActionAttributeIds { get; set; }
        public byte WorkflowActionId { get; set; }
        public Nullable<bool> isCharges { get; set; }
        public Nullable<bool> isDirections { get; set; }
        public Nullable<bool> isEquipment { get; set; }
        public Nullable<bool> isExclusions { get; set; }
        public Nullable<bool> isExpertise { get; set; }
        public Nullable<bool> isMaterialList { get; set; }
        public Nullable<bool> isMeasurements { get; set; }
        public Nullable<bool> isPublications { get; set; }
        public int MasterCompanyId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
