namespace DAL.Common
{
    public enum ModuleEnum
    {
        Customer=1,
        CustomerContact,
        Vendor,
        Employee,
        Publication,
        UnitOfMeasure,
        Manufacturer,
        Memo,
        ItemClassfication, 
        Site, 
        WareHouse,
        Location,
        ATAMainChapter,
        Shelf,
        AssetType,
        AssetIntangibleType,
        StageCode,
        GLAccountCategory,
        ExpenditureCategory,
        AssetAttributeType,
        AssetIntangibleAttributeType,
        ItemMaster,
        NhaTlaAltEquItemMapping,
    }
}
